### ISSUE TITLE
A question about the training data

### ISSUE THREAD

**Issue by kktsubota** [Dezhao-Wang/Neural-Syntax-Code#1]
Thank you for sharing the codes of your great work.
I have a question about the preparation of the training data.
Your paper said
> To make the model adapt to images of different resolutions, we down-sample the images to half of their resolutions as the augmentation of the training data

However, the down-scaling operation is not included in your codes.

Did you prepare 1,600 images as training data in total (800 original images and 800 down-scaled images)?
Moreover, I would appreciate it if you could share the code for the dataset preparation.

**Comment by Dezhao-Wang** [comment]
> Did you prepare 1,600 images as training data in total (800 original images and 800 down-scaled images)?

Yes, I simply downscaled the original 800 images and merged them with the original data together.

**Comment by kktsubota** [comment]
Thank you for your reply. I plan to try to reproduce your results.
