### ISSUE TITLE
Maybe some mistakes about testing.

### ISSUE THREAD

**Issue by dq0309** [Dezhao-Wang/Neural-Syntax-Code#2]
![f02f13398f8e94cc010400443bc91ec](https://user-images.githubusercontent.com/38873963/171866034-99a7058f-a626-4e25-9607-04d057876f46.png)
In the definition of _test_y_sampler_, maybe _b_, _h_, _w_ need to be replaced with _tb_, _th_, _tw_.
![a321f024979f78941e441d68ce3da66](https://user-images.githubusercontent.com/38873963/171866053-0bd95fce-61c4-4641-96e7-b5f6722b0cc6.png)
Here, maybe _y_sampler_ and _h_sampler_ need to be replaced with  _test_y_sampler_ and _test_h_sampler_.

**Comment by Dezhao-Wang** [comment]
Thanks for your comments. I will revise the code to avoid confusion. However, it actually doesn't affect testing. If you look inside BlockSample, you will find that only the channel dimension matters.
